# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4c5ee7520f2e1a81221c7b25e40be7475d5b8753da9d1699b7fd819d954623c44cff4bcc5391ba0d031a90a6375dcef36b49fddf6982e57940a37b7f8c9d527

test:
  secret_key_base: df391eb7b99af1a40bae6b8c32623417bb20ab3ff5a14d673454759463b8a7e10a5673e476a2bf72263d6f2474e17ce1a52406d3df2b811afb92e2b020ce06f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
